name: Change EC2 Instance Type

on:
  workflow_dispatch:
    inputs:
      instance_id:
        description: 'EC2 Instance ID'
        required: true
        type: string
      region:
        description: 'AWS Region'
        required: true
        type: string
        default: 'ap-south-1'
      instance_type:
        description: 'New EC2 Instance Type'
        required: true
        type: choice
        options:
          - t3.micro
          - t3.small
          - t3.medium
          - t3.large
          - t3.xlarge
          - t3.2xlarge
          - m5.large
          - m5.xlarge
          - m5.2xlarge

jobs:
  change-instance-type:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}

      - name: Stop EC2 instance
        run: |
          aws ec2 stop-instances --instance-ids ${{ github.event.inputs.instance_id }} --region ${{ github.event.inputs.region }}

      - name: Wait for instance to stop
        run: |
          aws ec2 wait instance-stopped --instance-ids ${{ github.event.inputs.instance_id }} --region ${{ github.event.inputs.region }}

      - name: Change instance type
        run: |
          aws ec2 modify-instance-attribute --instance-id ${{ github.event.inputs.instance_id }} --instance-type "{\"Value\": \"${{ github.event.inputs.instance_type }}\"}" --region ${{ github.event.inputs.region }}

      - name: Start EC2 instance
        run: |
          aws ec2 start-instances --instance-ids ${{ github.event.inputs.instance_id }} --region ${{ github.event.inputs.region }}